---
title: "Raw tournament results in table format"
author: "H.J. Poethke, A. Kubisch, O. Mitesser, T. Hovestadt"
subtitle: The evolution of density-dependent dispersal under limited information.
output:
  word_document: default
  pdf_document:
    keep_tex: yes
  html_document: default
---

```{r, echo=FALSE}

pair_base = c("L/TA", "L/TAE", "L/S", "TA/TAE", "TA/S", "TAE/S","L/Sm","TA/Sm","TAE/Sm")
sig_base = c(0, 12.5, 25)
info_base = c(0.2, 0.5, 0.8)

L = numeric()
TA = numeric()
TAE = numeric()
S = numeric()
Sm = numeric()

draw = numeric()
pairing = rep(pair_base,length(sig_base)*length(info_base))
sigma = rep(rep(sig_base,each=length(pair_base)),length(info_base))
info = rep(info_base,each=length(pair_base)*length(sig_base))

for (i in c("_i02","_i05","_i08")) {
  for (s in c("sig0","sig125","sig25")) {
    path = paste0(s,i,"/data/output.txt")
    data = read.table(path,header=T)
    path_Sm = paste0(s,i,"_Sm/data/output.txt")
    data_Sm = read.table(path_Sm,header=T)
    x = data$frac_s1
    y = data$frac_draw
    
    x_Sm = data_Sm$frac_s1
    y_Sm = data_Sm$frac_draw

    L = c(L,round(x[1:3]*100),"--","--","--",round((x_Sm[3])*100),"--","--")
    TA = c(TA, round((1-x[1]-y[1])*100), "--","--", round(x[4:5]*100), "--","--",round(x_Sm[5]*100),"--")
    TAE = c(TAE,"--",round((1-x[2]-y[2])*100),"--",round((1-x[4]-y[4])*100),"--",round(x[6]*100),"--","--",round(x_Sm[6]*100))
    S = c(S,"--","--",round((1-x[3]-y[3])*100),"--",round((1-x[5:6]-y[5:6])*100),"/","/","/")
    Sm = c(Sm,rep("/",6),round((1-x_Sm[3]-y_Sm[3])*100),
                         round((1-x_Sm[5]-y_Sm[5])*100),
                         round((1-x_Sm[6]-y_Sm[6])*100))
    draw = c(draw,y*100,y_Sm[c(3,5,6)]*100)
  }
}

results <- data.frame(I=info,sigma=sigma,pairing=pairing,draw=draw,TA=TA,TAE=TAE,L=L,S=S,Sm=Sm)

```

```{r pander, echo=F}
library(pander)
pander(results,caption="Raw tournament results.")
```
